### ISSUE TITLE
Greške koje se ispisuju prilikom prijave na sistem

### ISSUE THREAD

**Issue by AdinZuhric** [SoftverInzenjeringETFSA/SI2015Tim6#15]
Komponenta: Prijava na sistem

Opis problema: Prilikom pokušaja prijave na sistem, ispisuje se greška da password mora biti minimalno 8 znakova, iako je unijeto više od 8 znakova.

http://pokit.org/get/?48dffcd6a44e963b2040b2c7b81d3622.jpg

Koraci za reproduciranje problema:
1. Pokretanje aplikacije
2. Pokušavanje prijave na sistem

Dobijeni rezultat: 
Ispisuje se greška koja nije tačna.

Očekivani rezultat:
Pokretanje forme sistema.

**Comment by OmarDer** [comment]
Ispravljen je pogresan natpis na kontroli.

**Comment by ahusic** [comment]
Poruka  greške nije bila usklađena sa opisom problema. Poruka je nanovo formulisana kako bi dala bolji uvid u tip problema.
