### ISSUE TITLE
Nema mogucnosti povratka na pocetnu formu uposlenika prijavljenog kao Kasir

### ISSUE THREAD

**Issue by AdinZuhric** [SoftverInzenjeringETFSA/SI2015Tim6#19]
Komponenta:
Forma za kasira->Kreiranje računa

Opis problema:
Nakon sto se otvori forma kreiranje racuna, nema mogucnosti povratka na pocetnu formu.

Koraci za reproduciranje problema:
1. Prijaviti se na sistem kao Kasir.
2. Izabrati opciju "Kreiranje računa"
3. Zatvoriti datu formu.

Dobijeni rezultat:
Izlaz iz aplikacije.

Očekivani rezultat:
Povratak na pocetnu formu za Kasira.

**Comment by ahusic** [comment]
Property forme prilikom izlaska bio ostavljen na EXIT_ON_CLOSE
