### ISSUE TITLE
Password nije hashiran u bazi

### ISSUE THREAD

**Issue by LejlaNukic** [SoftverInzenjeringETFSA/SI2015Tim6#21]
Komponenta: Tabela uposlenik u bazi

commit ID: 606852e255534ced4bd4403773d26b4c0e3e8f83

Opis problema: Sifra za prijavu na sistem se nalazi u citljivom obliku u bazi, nije hashirana.

Koraci za reproduciranje problema:
1.Pokrenuti init skriptu u workbenchu
2.Kliknuti na ikonicu pored tabele uposlenik kako bi se vidio sadrzaj tabele uposlenik

Dobijeni rezultat: 
screenshot: http://pokit.org/get/?b7f92a9ee91431dc89825e75db30c964.jpg
Očekivani rezultat: hashirani podaci u koloni password

**Comment by OmarDer** [comment]
U SRS-u nije navedeno da ce sifre biti hashirane u bazi.
