### ISSUE TITLE
Neusaglasenost class dijagrama i modela

### ISSUE THREAD

**Issue by LejlaNukic** [SoftverInzenjeringETFSA/SI2015Tim6#22]
Komponenta: Klasa Uposlenik

commit ID: 950d06c3554182a4168743185055f93be47d4b92

Opis problema: Klasa uposlenik prikazana na klasnom dijagramu kao apstaktna klasa sa dvije naslijedjene klase, a u projektu je javna i nije nista nasljedjeno iz nje.

Koraci za reproduciranje problema:
1.Pogledati implementaciju klase Uposlenik

Dobijeni rezultat:
http://pokit.org/get/?32353e786f134d9795b8dd66c9f19b9a.jpg
Očekivani rezultat: Klasa Uposlenik apstraktna, iz nje dvije klase naslijedjene.

**Comment by OmarDer** [comment]
Previse vremena bi oduzelo popravljanje ovakve pogreske, s obzirom da vremenski interval namijenjen za ispravljanje bugova namjeravamo iskoristiti kako bismo popravili greske u funkcionalnostima i prilikom izvrsenja aplikacije.
