### ISSUE TITLE
Neusaglasenost ERD-a i tabela u bazi

### ISSUE THREAD

**Issue by LejlaNukic** [SoftverInzenjeringETFSA/SI2015Tim6#23]
Komponenta: Dokument Dizajn sistema i baza

commit ID: 950d06c3554182a4168743185055f93be47d4b92

Opis problema: U bazi postoji tabela stornoracun koja ne postoji na ERD dijagramu.

Koraci za reproduciranje problema:
1.Otvoriti dokument dizajna sistema i shemu baze
2.Uporediti to dvoje

Dobijeni rezultat:
http://pokit.org/get/?85acc5ced0cfae4201592a6f68b3a2e1.jpg
Očekivani rezultat: Tabela stornoracun na ERD-u ili da ne postoji ni u bazi.

**Comment by OmarDer** [comment]
Previse vremena bi oduzelo popravljanje ovakve pogreske, s obzirom da vremenski interval namijenjen za ispravljanje bugova namjeravamo iskoristiti kako bismo popravili greske u funkcionalnostima i prilikom izvrsenja aplikacije.
