### ISSUE TITLE
Validacija za JMBG nije uredu

### ISSUE THREAD

**Issue by LejlaNukic** [SoftverInzenjeringETFSA/SI2015Tim6#24]
Komponenta: interfejs za dodavanje novog korisnika

commit ID: 606852e255534ced4bd4403773d26b4c0e3e8f83

Opis problema: Prilikom dodavanja novog korisnika unesen JMBG koji se sastoji od 13 cifara, ali nije validan i ispisuje se ispravna poruka.Nakon toga pokusajmo dodati korisnika kod kojeg je JMBG:9999999999999 i nece prijaviti gresku.

Koraci za reproduciranje problema:
1.Logovati se kao korisnik sa privilegijom Sef
2.Kliknuti na dugme Dodavanje korisnika
3.U formi unijeti ime:Lejla, prezime: Nukic, JMBG:9999999999999 ili npr ovakav JMBG:
http://pokit.org/get/?7090f4516afdf60e52e25ae2d72a8b0d.jpg

Dobijeni rezultat:
http://pokit.org/get/?619fb5b48642f2565103a37f9ddfdf1b.jpg
ili npr ovo je takodjer validno:
http://pokit.org/get/?7090f4516afdf60e52e25ae2d72a8b0d.jpg
Očekivani rezultat: Prijava greske.

**Comment by ahusic** [comment]
Algoritam koji radi je ispravno radio, ali priznajem da je propust od mene, algoritam je nadograđen.
