### ISSUE TITLE
Za korisnicko ime koja zadovoljava format duzine, prijavljuje da nije adekvatna duzina

### ISSUE THREAD

**Issue by LejlaNukic** [SoftverInzenjeringETFSA/SI2015Tim6#25]
Komponenta: Interfejs za dodavanje novog korisnika

commit ID: 606852e

Opis problema: Prilikom unosa podataka za dodavanje novog korisnika, za ime koje je duze od tri slova i manje od 20 slova, sistem prijavljuje gresku da korisnicko ime treba biti duze od tri slova i manje od 20.

Koraci za reproduciranje problema:
1.Logovati se kao korisnik sa privilegijom sef
2.Kliknuti na dugme Dodavanje korisnika
3.Unijeti ime:Lejla, prezime:Nukic,korisnicko ime: lnukic2

Dobijeni rezultat:
http://pokit.org/get/?c6369ec4f8f3221554a90ab22ec60d58.jpg
Očekivani rezultat: Omogucen dalji unos podataka ili poruka sa drugacijim tekstom.

**Comment by ahusic** [comment]
Nije bug, piše više od 3 i manje od 20 SLOVA! Unesen je broj zajedno sa unosom slova.

**Comment by LejlaNukic** [comment]
Kolega, unesena je kombinacija koja ukljucuje vise od tri i manje od 20 slova i broj. Ovo je totalno drugaciji tip bug-a od onog koji je prijavljen za issue #26. Kod #26 poruke se na uklanjaju sa ekrana, jedino zajednicko u ovom bug-u sa tim jeste da se ispisuje poruka upozorenja, a poenta problema je sasvim drugacija.

**Comment by ahusic** [comment]
Kolegice nije Bug, molim Vas da prestanete govorit Bug, već vaša greška, ali da nije duplikat od #26.

**Comment by LejlaNukic** [comment]
Kolega, drago mi je da ste uocili gresku.  #26 i dalje stoji kao "invalid" iako se u navedenom commit-u poruke ne uklanjaju sa ekrana.

**Comment by LejlaNukic** [comment]
Kolega, 
Vi ocito imate problem sa razumijevanjem pojma bug kad izjavljujete ovakvo nesto:
http://pokit.org/get/?dc50c68466b1836bab855361911885ad.jpg
U slucaju da niste sigurni, predlazem da se konsultujete sa nekim od clanova Vaseg tima prije iznosenja ovakvih ili slicnih komentara. U krajnjem slucaju mozete se obratiti za pomoc asistentu ako sumnjate u odluku ostalih clanova tima. 
Ovakve izjave ne idu u prilog ni Vama, ni timu ciji ste clan.
