### ISSUE TITLE
Zbog pozicije poruka za validaciju polja, neka polja se ne mogu popuniti nikako i korisnik se ne moze dodati

### ISSUE THREAD

**Issue by LejlaNukic** [SoftverInzenjeringETFSA/SI2015Tim6#26]
Komponenta: Interfejs za dodavanje novog korisnika

commit ID: 606852e

Opis problema: Prilikom unosa podataka za dodavanje novog korisnika, u slucaju da neki od njih nije validan ispisuje se poruka o gresci, nakon sto pokusam da popravim taj unos i obrisem podatke koje sam ranije unijela

Koraci za reproduciranje problema:
1.Logovati se kao korisnik sa privilegijom sef
2.Kliknuti na dugme Dodavanje korisnika
3.Unijeti ime:Lejla, prezime:Nukic,JMBG:9999999999999, unijeti username:lnukic2, ispise se ova poruka:http://pokit.org/get/?5867c931d30f7cfa5c199ca32574969b.jpg
4.Obrisati to korisnicno ime i unijeti korisnicko ime:djadajoadjaod
5.Zbog ispisane poruke koja stoji ne moze se unijeti broj telefona

Dobijeni rezultat:
http://pokit.org/get/?132211a1ea1de25e156f7127ad4761af.jpg
Očekivani rezultat: Omogucen dalji unos podataka i uklonjena poruka da username nije validan.

**Comment by ahusic** [comment]
Nije Bug već se dešavaju ovakve stvari jer ih izazivate namjerno, unosite nevalidne podatke, zatvarate forme, dok su poruke aktivne, pri čemu se može desiti ali ne uvijek preklapanje, dogodi se da negdje u memoriji ostane nešto. Otići na Project-Clean i sve ce radit OK.

**Comment by LejlaNukic** [comment]
Kolega, ovaj bug nije duplikat sa #25, objasnjeno je u komentaru kod #25 zasto, u slucaju da me niste zeljeli shvatiti. Molit cu Vas da jos jednom razmotrite pomno ovu situaciju.
