### ISSUE TITLE
Poruke o greskama se ne uklanjaju sa ekrana

### ISSUE THREAD

**Issue by LejlaNukic** [SoftverInzenjeringETFSA/SI2015Tim6#27]
Komponenta: Interfejs za dodavanje novog korisnika

commit ID: 606852e

Opis problema: Prilikom unosa podataka za dodavanje novog korisnika, u slucaju da neki od njih nije validan ispisuje se poruka o gresci, nakon sto pokusam da popravim taj unos i obrisem podatke koje sam ranije unijela

Koraci za reproduciranje problema:
1.Logovati se kao korisnik sa privilegijom sef
2.Kliknuti na dugme Dodavanje korisnika
3.Unijeti 
ime:Lejla, 
prezime:Sef,
JMBG:9999999999999, 
username:SefAdmin,
broj telefona:+00000-000-000,
datum rodjenja:1991-09-02,
password i ponovljeni password:adminSef12345,
uloga:Sef
4.Izmijeniti username na:SefAdmin1
5.Klik na dugme Dodaj novog korisnika

Dobijeni rezultat:
http://pokit.org/get/?d5d6c9bc039959b0d0a4fa6ace79adc0.jpg
Očekivani rezultat: Dodan korisnik ili jedna odgovarajuca poruka :)

**Comment by OmarDer** [comment]
Slijedom gore navedenih koraka nismo uspjeli da uocimo navedeni propust
