### ISSUE TITLE
Interfejs bi prema SRS-u trebao biti na bosanskom jeziku

### ISSUE THREAD

**Issue by LejlaNukic** [SoftverInzenjeringETFSA/SI2015Tim6#29]
Komponenta: Interfejs za prijavu na sistem, interfejs za dodavanje novog korisnika

commit ID: 606852e

Opis problema: Neke labele su na engleskom jeziku.
Koraci za reproduciranje problema:
1.Logovati se kao korisnik sa privilegijom sef
2.Kliknuti na dugme Dodavanje korisnika

Dobijeni rezultat:
http://pokit.org/get/?1fe69004ac77f7a8764049ed82d62614.jpg,
http://pokit.org/get/?38679581ff1f62e0a969d2e4fef1d23b.jpg
Očekivani rezultat: Interfejs u potpunosti na bosanskom jeziku.

**Comment by ahusic** [comment]
Da li je Bug ili je traženje dlake u jajetu.
