### ISSUE TITLE
Korisnik moze obrisati sam sebe

### ISSUE THREAD

**Issue by LejlaNukic** [SoftverInzenjeringETFSA/SI2015Tim6#30]
Komponenta: Interfejs za dodavanje novog korisnika

commit ID: 606852e

Opis problema: U slucaju da postoji samo jedan korisnik u sistemu, moze obrisati sam sebe i nakon toga prijava na sistem nije moguca, a samim tim ni kreiranje korisnika.
Koraci za reproduciranje problema:
1.Logovati se kao korisnik sa privilegijom sef
2.Kliknuti na dugme Brisanje korisnika
3.U formu Brisanje korisnika unijeti JMBG:9999999999999
4.Kliknuti na dugme Pronadji
5.Kliknuti na dugme Prikazi rezultate pretrage
6.Kliknuti na dugme Izbrisi na formi Brisanje korisnika
7. Nakon toga na MessageBox-u:http://pokit.org/get/?a68fe7db311ed50a2bd919af6ce66562.jpg, kliknemo na OK

Dobijeni rezultat:
Korisnik obrisan iz baze

Očekivani rezultat: Obavijest da je to jedini korisnik na sistemu i ne preporucuje se brisanje ili samo poruka o nemogucnosti brisanja.

**Comment by ahusic** [comment]
commit  4315d01 problem uspješno rješen
