### ISSUE TITLE
Dugme Odjava, Izvjestaji i Kraj smjene na formi za sefa ne rade

### ISSUE THREAD

**Issue by LejlaNukic** [SoftverInzenjeringETFSA/SI2015Tim6#31]
Komponenta: Interfejs za sefa

commit ID: d8619f435b949dfc6c8633aa5fb86a4014ad1ccf

Opis problema: Nakon sto se uspjesno logujemo na sistem kao korisnik sa privilegijom sef, klikom na dugme Odjava korisnik se ne odjavljuje sa sistema.
Koraci za reproduciranje problema:
1.Prijaviti se na sistem kao korisnik sa privilegijom sef
2.Kliknuti na dugme Odjava ili Izvjestaji ili Kraj smjene

Dobijeni rezultat:
Nista se ne desi.

Očekivani rezultat: Obavijest o odjavi sa sistema ili prikaz forme za prijavu.

**Comment by OmarDer** [comment]
Duplikat sa issue-om #20 .
