### ISSUE TITLE
Dugmad za kreiranje izvjestaja i provjeru stanja artikla nisu funkcionalna

### ISSUE THREAD

**Issue by LejlaNukic** [SoftverInzenjeringETFSA/SI2015Tim6#32]
Komponenta: Interfejs za kasira

commit ID: d8619f4

Opis problema: Nakon sto se ulogujemo kao korisnik sa privilegijom Kasir, klikom na dugmad Kreiranje izvjestaja po zavrsetku smjene i Provjera stanja artikla, ne desi se nista. 
Koraci za reproduciranje problema:
1.Prijaviti se na sistem kao korisnik sa privilegijom "Kasir"
2.1.Kliknuti na dugme Kreiranje izvjestaja po zavrsetku smjene ili 
2.2.Kliknuti na dugme Provjera stanja artikla

Dobijeni rezultat:
Nista se ne desi i dalje vidimo samo glavnu formu za kasira:
http://pokit.org/get/?d756e73d28485d4e517968bf4ce1c51d.jpg

Očekivani rezultat: Otvaranje nove forme za koristenje navednih funkcionalnosti.

**Comment by OmarDer** [comment]
Duplikat sa #20 .
