### ISSUE TITLE
Ne radi dugme za prikaz kategorije

### ISSUE THREAD

**Issue by cenga** [SoftverInzenjeringETFSA/SI2015Tim6#34]
Komponenta: Interfejs za sefa
commit ID: d8619f4

Koraci za reproduciranje problema:
- Ulogujemo se kao šef
- Pritisnemo na kategorije
- Izaberemo jednu od kategorija (ako nema dodamo novu)
- Zatim pritisnemo dugme "Prikazi"

Rezultat: Ništa se ne desi nakon klika na dugme

Očekivani rezultat: Vjerovatno bi trebalo prikazai detalje kategorije

**Comment by OmarDer** [comment]
Ne, to uopste ne bi trebalo ni da se desi, dugme "Prikazi" prikazuje listu kategorija koje su pohranjene, a ne pojedinosti o kategoriji.
