### ISSUE TITLE
Polja u tabeli za brisanje artikla, pretragu artikla i promjenu popusta se mogu mijenjati(editabilna su)

### ISSUE THREAD

**Issue by LejlaNukic** [SoftverInzenjeringETFSA/SI2015Tim6#36]
Komponenta: Interfejs za brisanje artikla

commit ID: d8619f4

Opis problema: Po zavrsetku pretrage artikala, u tabeli se pojavljuje artikal sa odgovarajucim bar kodom, medjutim polja tabele se mogu mijenjati.

Koraci za reproduciranje problema:
1.Prijaviti se na sistem kao korisnik sa privilegijom sef
2.Kliknuti na dugme za Brisanje artikla
3.Unijeti bar kod nekog od dodanih artikala, ja sam npr. unijela bar kod:
3858890970005
4.Kliknuti na dugme Pretrazi
5.Po zavrsetku pretrage kliknuti na neku celiju u tabeli.

Napomena:Ista stvar je i sa ostale dvije navedene tabele.

Dobijeni rezultat:
http://pokit.org/get/?4fc8b06d8e42b3f9bb1dfd3e8fab1540.jpg

Očekivani rezultat: Polja tabele nisu editabilna.

**Comment by OmarDer** [comment]
Jesu editabilna, ali to ne utice na dalje izvrsavanje programa, rezultate operacija, ti podaci nece biti unijeti u bazu, itd.
