### ISSUE TITLE
Prilikom brisanja artikla, nema nikakve poruke u slucaju da se pretraga vrsi po bar kodu koji ne postoji ili nije validan.

### ISSUE THREAD

**Issue by LejlaNukic** [SoftverInzenjeringETFSA/SI2015Tim6#38]
Komponenta: Interfejs za brisanje artikla

commit ID: d8619f4

Opis problema: U slucaju da se u polje za pretragu po bar kodu unese bar kod koji ne postoji u sistemu ili bar koji nije validan, i klikne se na dugme Pretrazi, nema nikakvog obavjestenja ili poruke o gresci za unos.

Koraci za reproduciranje problema:
1.Prijaviti se na sistem kao korisnik sa privilegijom sef
2.Kliknuti na dugme za Brisanje artikla
3.Unijeti bar kod koji ne postoji u sistemu ili bilo kakvu kombinaciju znakova.
4.Kliknuti na dugme Pretrazi

Dobijeni rezultat:
http://pokit.org/get/?e02e94f3f5bd7db708f7ef7e7c401153.jpg

Očekivani rezultat: Obavijest da ne postoji artikal sa unesenim bar kodom ili da format bar koda nije odgovarajuci.

**Comment by OmarDer** [comment]
U SRS-u nije navedeno ponasanje u tom slucaju, a konkretno ne desi se nista, dakle ukoliko je neispravan barkod ili ga nema ne desi se nista, ukoliko je ispravan u tabeli se prikazu rezultati pretrage.
