### ISSUE TITLE
Dodavanje stavke računa ne radi

### ISSUE THREAD

**Issue by cenga** [SoftverInzenjeringETFSA/SI2015Tim6#39]
Komponenta: Interfejs za sefa
commit ID: d8619f4

Koraci za reproduciranje problema:
- Ulogujemo se kao šef
- Pritisnemo kreiranje racuna
- Kliknemo na "Dodaj stavku"

Rezultat: Ništa se ne desi nakon klika na dugme

Očekivani rezultat: Trebalo bi biti omogućeno dodavanje nove stavke računa

**Comment by vhrustic** [comment]
46491da7cc8aa54b84268aa3eed4598706ee848b

**Comment by vhrustic** [comment]
Đe šta kako? jesi unio prvo barkod od artikla? ne mogu iz opisa da zaključim puno ali pretpostavljam da nisi unio barkod artikla tako da i nema šta da se doda u listu., znam da je barem ovo radilo ispravno.

**Comment by cenga** [comment]
Jesam unio i barkod artikla ali se ništa ne desi nakon klika na dugme dodaj stavku. A i da se desi, princip dodavanja je pogrešan jer se mora pamtiti 13-cifreni barkod za svaki artikal, a artikala može biti na hiljade u bazi podataka.
