### ISSUE TITLE
Prilikom dodavanja artikla izbacuje se poruka "Potvrda passworda nije uredu"

### ISSUE THREAD

**Issue by cenga** [SoftverInzenjeringETFSA/SI2015Tim6#40]
Komponenta: Interfejs za sefa
commit ID: d8619f4

Koraci za reproduciranje problema:
- Ulogujemo se kao šef
- Pritisnemo na dodavanje artikla
- Unesemo nevalidnu vrijednost za količinu

Rezultat: Izbaci upozorenje "Potvrda passworda nije uredu!" (vjerovatno se ovo dešava kada se prethodno pokušao dodati uposlenik pa u jednom trenutku passwordi nisu bili jednaki!)

![artikal](https://cloud.githubusercontent.com/assets/11297482/15337887/ee18e456-1c7d-11e6-9f12-3dd6740feef3.jpg)

Očekivani rezultat: Ne bi trebalo prikazati to upozorenje

**Comment by vhrustic** [comment]
blago firmi koju mi zaobiđemo :D

**Comment by OmarDer** [comment]
Objasnjenje #42 .
