### ISSUE TITLE
Cijena artikla koju unesemo i cijena u tabeli koja se dobije prilikom pretrage artikla se ne poklapaju.

### ISSUE THREAD

**Issue by LejlaNukic** [SoftverInzenjeringETFSA/SI2015Tim6#41]
Komponenta: Interfejs za pretragu artikla.

commit ID: d8619f4

Opis problema: Prvo dodamo artikal kroz interfejs za dodavanje artikla, zatim kroz interfejs za brisanje artikla pretragom pronadjemo dodani artikal. Iznos u koloni cijena se ne poklapa sa cijenom koju smo unijeli prilikom dodavanja artikla.

Koraci za reproduciranje problema:
1.Prijaviti se na sistem kao korisnik sa privilegijom sef
2.Dodati artikal sa ovim podacima:http://pokit.org/get/?83ea0d772a1ba4965a5082a7ca2535d4.jpg, kroz interfejs za dodavanje artikla
-Napomena: U slucaju da cijenu unosimo sa zarezom ispisuje se sljedeca poruka:
http://pokit.org/get/?3365a879ecb4d2bbc69eecda08a24fa1.jpg
3.Vratiti se na glavnu formu i kliknuti na dugme Pretraga artikla
4.Odabrati Naziv za nacin pretrage i unijeti naziv artikla: Kahva Vispak
4.Kliknuti na dugme Pretrazi

Dobijeni rezultat:
http://pokit.org/get/?05acd9181b82293113711200c86d5ae0.jpg

Očekivani rezultat:
Iznos u kolonu cijena bi trebao biti 5.50.

**Comment by OmarDer** [comment]
Zatvoreno u commitu #30a0cb46c6f4e1fd50d5028b4ccc251b23b75f7b .
