### ISSUE TITLE
Prilkom unosa popusta za nevalidnu vrijednost popusta izbaci dva upozorenja o grešci, jedno preko drugog

### ISSUE THREAD

**Issue by cenga** [SoftverInzenjeringETFSA/SI2015Tim6#42]
Komponenta: Interfejs za sefa
commit ID: d8619f4

Koraci za reproduciranje problema:
- Ulogujemo se kao šef
- Pritisnemo na popust
- Za polje "Iznos popusta" unesemo nevalidnu vrijednost

Rezultat: Izbace se dva upozorenja na greške, jedna preko druge

![popust1](https://cloud.githubusercontent.com/assets/11297482/15338188/101388da-1c7f-11e6-9214-8d5d6f130ef1.jpg)

Očekivani rezultat: Trebalo bi prikazati samo jedno upozorenje

**Comment by ahusic** [comment]
Nije bug već do ecplise-a zatvoriti aplikaciju, otići na project- clean nakon toga pokrenuti i sve će biti OK, kao i u slučaju da se dogodi negdje drugo na nekoj formi.

**Comment by ahusic** [comment]
Bug se dešava zbog Vas. Namjerno unosite pogrešne podatke, i tako ostavljene forme sa neispravnim unosima i porukama gasite te otvarate nove forme gdje može doći do preklapanja poruka. Ukoliko Sve radite prema opisu kako je navedeno, neće doći do ovog. Problem je moguće rješit tako da se uradi Project-Clean pri čemu se ne bi ovo trebalo događati
