### ISSUE TITLE
Klikom na dugme "Promijeni popust" se izbace dvije greške

### ISSUE THREAD

**Issue by cenga** [SoftverInzenjeringETFSA/SI2015Tim6#44]
Komponenta: Interfejs za sefa
commit ID: d8619f4

Koraci za reproduciranje problema:
-   Ulogujemo se kao šef
-   Pritisnemo promjena popusta

Rezultat: Bez odabira i jednog popusta, odmah pritisnemo "Promijeni Popust" i izbaci nam dvije greške

![izmjena_popusta](https://cloud.githubusercontent.com/assets/11297482/15338462/4226e0b4-1c80-11e6-9b30-14fe411e1598.png)

Očekivani rezultat: Greške ne bi trebale biti prikazane

**Comment by OmarDer** [comment]
Slijedom gore navedenih aktivnosti, nisam uspio da uocim navedeni bug.
