### ISSUE TITLE
Dugme Dodaj stavku, Obrisi stavku, Stampaj racun i Reklamni racun nisu funkcionalna na oba interfejsa(sef i kasir).

### ISSUE THREAD

**Issue by LejlaNukic** [SoftverInzenjeringETFSA/SI2015Tim6#47]
Komponenta: Interfejs za kreiranje racuna

commit ID: d8619f4

Opis problema: Nakon sto se unesemo barkod artikla koji postoji u sistemu i podatak o kolicini i kliknemo na dugme Dodaj stavku ne desi se nista.
Koraci za reproduciranje problema:
1.Prijaviti se na sistem kao korisnik sa privilegijom sef
2.Kliknuti na dugme Kreiranje racuna
3.Unijeti bar kod artikla kojeg smo vec ranije dodali, npr:
1234567890004
4.Unijeti kolicinu: 3 (validna je obzirom da smo prilikom dodavanja artikla stavili da je 15.
5.Kliknuti na dugme Dodaj stavku 
-Napomena 1: Isto vazi i za dugmad Obrisi stavku, Stampaj racun i Reklamni racun.
=Napomena 2:Isto vazi i za interfejs korisnika sa privilegijom kasir.

Dobijeni rezultat:
http://pokit.org/get/?14a75a86be401037a0585f0482be9c4a.jpg

Očekivani rezultat: Stavka racuna se dodala u tabelu na formi, stavka se moze brisati.

**Comment by vhrustic** [comment]
nešto je po(na)pravljeno:Storno racun, dodaj stavku, orisi stavku, također neke stvari su iskodirane ali ne rade prema očekivanja, generalno funkcionalnost stampanja racuna nije kompletna
