### ISSUE TITLE
Izgled forme za šefa nije ista kao u dizajnu sistema

### ISSUE THREAD

**Issue by mpeljto1** [SoftverInzenjeringETFSA/SI2015Tim6#51]
Komponenta: Interfejs za šefa
commit id: d8619f435b949dfc6c8633aa5fb86a4014ad1ccf

Koraci za reproduciranje problema:
- Ulogujemo se kao šef

Rezultat: http://pokit.org/get/?a75ebf652866c3166278052c7ed2ff3d.jpg
Očekivani rezultat: http://pokit.org/get/?da592ae38158524f19d95c04e48c2425.jpg

**Comment by ahusic** [comment]
Nije bug
