### ISSUE TITLE
Nema main metode koja pokreće login

### ISSUE THREAD

**Issue by mpeljto1** [SoftverInzenjeringETFSA/SI2015Tim6#52]
Komponenta: Pos-kasa aplikacija
commit id: d8619f435b949dfc6c8633aa5fb86a4014ad1ccf

Koraci za reproduciranje problema:
- U eclipsu kliknuti na run dugme.

Rezultat: ispiše se Hello world Ramiza! 
Očekivani rezultat: prikaz login forme.

**Comment by ahusic** [comment]
Redosljed Run configurations je bio promijenjen u toj verziji commita koji ste povukli. Bug bi bio da aplikacija ne starta nikako, ali  aplikacija uredno starta pri čemu se koristi  LoginKontroler  kao starting point aplikacije.
