### ISSUE TITLE
Dodavanje kategorije u praznu bazu postavlja id različit od 1

### ISSUE THREAD

**Issue by mpeljto1** [SoftverInzenjeringETFSA/SI2015Tim6#54]
Komponenta: Kategorije
commit id: d8619f4

Koraci za reproduciranje problema
Ako u bazi postoji unesenih kategorija obrisati ih pomocu dugmeta Obrisi.
Unijeti novu kategoriju sa dugmetom dodaj.
Obrisati unesenu kategoriju.
Ponovo unijeti kategoriju.

Rezultat: id unesene kategorije nije 1
Očekivan rezultat: id bi trebao biti 1 ako imamo jednu kategoriju u bazi.

**Comment by OmarDer** [comment]
To je posao koji se automatski odradi od strane MySQL-a i Hibernate-a putem njihovih sekvenci, nikako ne utice na rad programa.
