### ISSUE TITLE
Promjena količine na kreiranju računa izaziva error

### ISSUE THREAD

**Issue by mpeljto1** [SoftverInzenjeringETFSA/SI2015Tim6#55]
Komponenta: Kreiranje računa
commit id: d8619f4

Koraci za reproduciranje problema:
logujemo se kao šef.
kliknemo na kreiranje računa.
promijenimo količinu.

Rezultat: http://pokit.org/get/?15d022bec86ecbb9f4f24c15fad9b2cf.jpg

**Comment by vhrustic** [comment]
46491da7cc8aa54b84268aa3eed4598706ee848b
