### ISSUE TITLE
Nije ispunjen nefunkcionalni zahtjev 3.3.1

### ISSUE THREAD

**Issue by mpeljto1** [SoftverInzenjeringETFSA/SI2015Tim6#58]
Ccommit ID: d8619f435b949dfc6c8633aa5fb86a4014ad1ccf

Opis problema:
U srsu je navedeno:Postojat će opcija “pomoć” za pružanje osnovnih informacija korisnicima što nije ispunjeno.

Koraci za reproduciranje problema:
1. Login na sistem
2. Otvoriti bilo koji prozor

Screenshot:
http://pokit.org/get/?8976eda8efc80e29151e600a20f51573.jpg -iz srsa

Dobijeni rezultat:
Nema opcije pomoći na ekranima

Očekivani rezultat:
Opcija Pomoć na ekranima

**Comment by rhoso1** [comment]
Dodana opcija pomoci na formi "OpcijeSefa", ostale forme su jednostavne i nema potrebe za tu opciju
