### ISSUE TITLE
Neusaglašenost Opisa formi u Dizajnu sistema i formi u aplikaciji

### ISSUE THREAD

**Issue by DinoBabahmetovic** [SoftverInzenjeringETFSA/SI2015Tim6#59]
Komponenta: Dokument Dizajn sistema i FormaKategorije

Commit ID: 970906b0896ad11a2ae5194960b10895a996edb9

Opis problema: Forma Kategorije se nigdje ne spominje u dizajnu sistema

Koraci za reproduciranje problema:
1.Otvoriti dokument Dizajna sistema i Source kod
2.Uporediti to dvoje

Dobijeni rezultat:
http://pokit.org/get/?44bb73e320ba03b76449fbedb1ea7eb9.jpg
Očekivani rezultat:
Postojanje Forme kategorija u Dizajnu sistema ili nepostojanje u aplikaciji

**Comment by OmarDer** [comment]
Vremenski je prezahtjevno promijeniti to, s obzirom na neophodne popravke vaznijih elemenata koji uticu na samu funkcionalnost.
