### ISSUE TITLE
Nepostojanje validacije datuma na formama za izvjestaje

### ISSUE THREAD

**Issue by DinoBabahmetovic** [SoftverInzenjeringETFSA/SI2015Tim6#60]
Komponenta: Forma IzvjestajOBrojuProdatih, IzvjUkupanPromet, IzvjUkupanPrometpoNP

Commit ID: 970906b0896ad11a2ae5194960b10895a996edb9

Opis problema: Moguće je unijeti datum OD koji je poslije datuma DO prilikom zahtjeva za izvještajem o broju prodatih, a da nas ne upozori o grešci

Koraci za reproduciranje problema:
1. Pokrenuti formu IzvjestajOBrojuProdatih
2. Unijeti određeni datum od npr. 9. Maj 2016.
3. Unijeti datum do koji je poslije datuma od npr. 8. Maj 2016.
4. Unijeti neki broj u polje Top
5. Kliknuti na dugme Prikazi izvjestaj

Dobijeni rezultat:
http://pokit.org/get/?09280c4bdc4616719d6426952760dca9.jpg
Očekivani rezultat:
Poruka o grešci i zahtjev za ponovnim unosom ispravnog datuma

**Comment by vhrustic** [comment]
fb92bd76750aa4eb9502c9f89db62d67d23ec80b
