### ISSUE TITLE
Moguće kupiti više artikala nego što ima u zalihama

### ISSUE THREAD

**Issue by DinoBabahmetovic** [SoftverInzenjeringETFSA/SI2015Tim6#62]
Komponenta: Forma za Kreiranje Racuna

Commit ID: 970906b0896ad11a2ae5194960b10895a996edb9

Opis problema: Moguće je dodati stavku računa čija je količina veća od stanja u zalihama, bez javljanja greške.

Koraci za reproduciranje problema: 
1. Kreirati artikl u bazi i staviti mu barkod npr 2222222222222 i stanje zalihe npr 5
2. Pokrenuti formu za kreiranje racuna
3. Unijeti barkod artikla
4. Unijeti količinu 7 npr.
5. Kliknuti na dugme Dodaj stavku

Dobijeni rezultat:
Stavka se normalno dodala u račun http://pokit.org/get/?068e73bf92ada49831d143f2a5671673.jpg
Očekivani rezultat:
Poruka o grešci.

**Comment by vhrustic** [comment]
46491da7cc8aa54b84268aa3eed4598706ee848b
