### ISSUE TITLE
Nemoguće unijeti popust koji je decimalni broj

### ISSUE THREAD

**Issue by DinoBabahmetovic** [SoftverInzenjeringETFSA/SI2015Tim6#63]
Komponenta: Forma za dodavanje popusta

Commit ID: 970906b0896ad11a2ae5194960b10895a996edb9

Opis problema: Ukoliko želim unijeti popust od 2.5 % javlja se poruka o greški koja kaže da popust mora biti broj.

Koraci za reproduciranje problema:
1. Pokrenuti formu za kreiranje popusta
2. Popuniti polja za datume i opis
3. Unijeti iznos popusta od 2.5 %
4. Kliknuti na dugme Kreiraj Popust

Dobijeni rezultat:
http://pokit.org/get/?5947bfbfffbbfcd46eded2f188ad6fe6.jpg
Očekivani rezultat:
Uspješno kreiranje popusta

**Comment by ahusic** [comment]
Naravno da nije moguće, iz razloga što pri našem dizajnu nije ni zamišljeno da može. Praksa je da popusti u marketima budu 5% 10% 20%, odnosno uglavnom cijeli brojevi.
