### ISSUE TITLE
Nemoguće unijeti vrijeme završetka smjene

### ISSUE THREAD

**Issue by DinoBabahmetovic** [SoftverInzenjeringETFSA/SI2015Tim6#64]
Komponenta: Forma za zaključivanje smjene

Commit ID: 970906b0896ad11a2ae5194960b10895a996edb9

Opis problema: Ne mogu unijeti vrijeme zavrsetka smjene jer je moguće izabrati samo datum sa kalendara

Koraci za reproduciranje problema:
1. Pokrenuti formu Zakljucivanje

Dobijeni rezultat:
Nemogućnost unošenja vremena završetka smjene: http://pokit.org/get/?b51cc7cc1828dd7ace9134d3389d98c9.jpg
Očekivani rezultat:
Moguće unijeti vrijeme završetka smjene kroz neku drugu vrstu inputa

**Comment by ahusic** [comment]
Nije potrebno nikako ni unosit u tome je bit, to je uklonjeno zamijenjeno sa potvrdom DA NE opcija.

**Comment by DinoBabahmetovic** [comment]
pa znaci da je bug jer je vasa greska sto ste stavili tu opciju ?

**Comment by vhrustic** [comment]
4315d0184f0ac79ff1d0e7667e6ca28ad6c296fa
