### ISSUE TITLE
Ne radi funkcionalnost zaključivanja smjene

### ISSUE THREAD

**Issue by DinoBabahmetovic** [SoftverInzenjeringETFSA/SI2015Tim6#65]
Komponenta: Forma za zakljucivanje smjene

Commit ID: 970906b0896ad11a2ae5194960b10895a996edb9

Opis problema: Ukoliko zelim zakljuciti smjenu, ne dobijem nikakav odziv, niti da je uspjesno zakljucena niti da nije

Koraci za reproduciranje problema:
1. Pokrenuti formu za Zakljucivanje smjene
2. Unijeti neke podatke za Datum i Vrijeme zavrsetka smjene
3. Kliknuti na dugme Zakljuci smjenu

Dobijeni rezultat:
Ništa se nije desilo, tj. korisnik ne zna da li je smjena zakljucena ili ne
Očekivani rezultat:
Poruka o ishodu aktivnosti zakljucivanja

**Comment by ahusic** [comment]
commit 4315d01
