### ISSUE TITLE
Validacija polja Broj tel. na formi Dodavanje novog korisnika

### ISSUE THREAD

**Issue by ArminK91** [SoftverInzenjeringETFSA/SI2015Tim6#66]
Komponenta: Forma za dodavanje novog korisnika

Commit ID: 970906b

Opis problema: Validacija ne radi, npr. ako pokusam unijeti svoj broj telefona nece ga prihvatiti. Npr. +38760-347-1608, dok ce na primjer prihvatiti +38760-347-160.

Koraci za reproduciranje problema:
1. Pokrenuti formu za Dodavanje novog korisnika
2. Unijeti podatke, između ostalog i broj telefona
3. Kliknuti na dugme Dodaj novog korisnika

Dobijeni rezultat:
Ispisuje poruku o tome da polje broj telefona nije validno.
Očekivani rezultat:
Poruka o validno unesenom broju telefona

**Comment by ahusic** [comment]
Niste se ispravno izrazili pod broj 1.validacija radi, drugo format vašeg broja ne podrzava aplikacija žao mi je. Novom verzijom update-a ćemo se potruditi da to omogućimo. Žao nam je što to nije omogućeno trenutno, ali imali smo bitnijih stvari na umu od toga. Trebao bih omogućiti da podržava sve moguće brojeve  i operatere, ali nisam u mogućnosti. A naravno da će prihvatit jer format mora biti kao što piše +xxxxx-xxx-xxx
