### ISSUE TITLE
Kreiranje popusta sa besmislenim datumima

### ISSUE THREAD

**Issue by ArminK91** [SoftverInzenjeringETFSA/SI2015Tim6#68]
Komponenta: Forma za kreiranje popusta

Commit ID: 970906b

Opis problema: Moguće je kreirati popust sa REALNO nerealnim datumima.
Npr: početak akcije 2.02.2016 a kraj akcije može se definisati na 26.05.2030 godine.

Koraci za reproduciranje problema:
1. Pokrenuti formu Popust
2. Unijeti podatke već navedene u "Opis problema"
3. Odabrati opciju Kreiraj popust

Dobijeni rezultat:
http://pokit.org/get/?0dba4a9f6ee2dea35ff5a2fafe370406.jpg

Očekivani rezultat:
Poruka o besmislenosti unošenja ovakvih podataka i kreiranja ovakvih popusta.

**Comment by OmarDer** [comment]
Duplikat sa #43
