### ISSUE TITLE
Kreiranje računa

### ISSUE THREAD

**Issue by ArminK91** [SoftverInzenjeringETFSA/SI2015Tim6#69]
Komponenta: Forma za kreiranje računa

Opis problema: Ako pokrenemo aplikaciju i pritisnemo na dugme "kreiranje računa" otvara se prozor sa mogućnostima kreiranja istog, međutim ako krenemo odmah mijenjati polje "količina" aplikacija baca exception koji nije hendlan,nemoguće je korištenje tog prozora, ali je moguće se vratiti na glavni prozor "opcije šefa" i aplikacija nastavlja rad.

Koraci za reproduciranje problema:
1. Pokrenuti formu Kreiranje računa
2. Mijenjati polje "Količina"

Dobijeni rezultat:
Pojavljuje se Exception "NullPointerException" koji nije hendlan te je nemoguće dalje koristiti ovu formu.
http://pokit.org/get/?3e1f4ba449c9914716d625093e111f65.jpg
Očekivani rezultat:
Validacija polja količina.

**Comment by vhrustic** [comment]
46491da7cc8aa54b84268aa3eed4598706ee848b

**Comment by vhrustic** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim6/issues/55
