### ISSUE TITLE
Validacija kod unosa lozinke, pri dodavanju novog korisnika

### ISSUE THREAD

**Issue by ArminK91** [SoftverInzenjeringETFSA/SI2015Tim6#71]
Komponenta: Forma za dodavanje novog korisnika

Commit ID: 970906b

Opis problema: Ako pokušamo unijeti/registrovati novog korisnika sa njegovim podacima sve teče po planu do unosa lozinke.
Naime ako unesemo lozinku npr. (predpostavimo da poštuje pravila validacije velika,mala slova itd.)
BegoBegic01 u polje "Lozinka", a nakon toga pokušamo unijeti u polje "potvrda lozinke" begoBegic99, validacija će nas spriječiti u tome, međutim ako ispravimo polje "potvrda lozinke" u BegoBegic01 tada ćemo biti u mogućnosti dodati novog korisnika i validacija prolazi, ali ako slučajno nakon toga ponovo unesemo neku izmjenu u polje "Lozinka" tada validacija ne radi i moguće je pritisnuti na dugme "dodaj novog korisnika" nakon čega kad se klikne korisnik bude dodan u bazu.

Koraci za reproduciranje problema:
1. Pokrenuti formu dodavanje novog korisnika
2. Slijediti proceduru navedenu u "opis problema".

Dobijeni rezultat:
Poruka u uspješno izvršenoj akciji dodavanja  korisnika: http://pokit.org/get/?0be3149255e9ef10e09d99f2696f3cea.jpg
Očekivani rezultat:
Validacija navedenih polja za unos, i obavjest o zabrani vršenja ovakvih malverzacija.

**Comment by ahusic** [comment]
:+1: da kad sam omogućio da korisnik može popravit lozinku nisam izvršio ponovnu cross validaciju obratno
